name: CI

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
      - run: make test
      - run: make format-check
